# Generated by Django 5.0.1 on 2024-01-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_f_guests',
            new_name='no_of_guests',
        ),
    ]
